name: Deploy to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Simple deploy with git
        uses: rdarida/simple-github-pages-deploy-action@v1
        with: # optional
          git-user: '<your GitHub username>'
          git-email: '<your email address>'
          git-base-folder: '<output folder of your build>'
          commit-message: '<your commit message>'
          branch: '<target branch for deployment>'
